version: '3.7'
services:
  iby-startknet-front:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    container_name: iby-startknet-front
    command: node_modules/.bin/next start
    working_dir: /opt/web
    image: iby-startknet-front
    ports:
      - 127.0.0.1:4000:3000
    networks:
      - iby-startknet-front

networks:
  iby-startknet-front:
    driver: bridge
