import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { useState } from "react";

export default function Home() {
  const [amount, setAmount] = useState(0);
  const [pk, setPK] = useState("");
  const [showModal, setShowModal] = useState(false);

  function handleChangeAmount(e) {
    setAmount(e.target.value);
  }
  function handleChangePK(e) {
    setPK(e.target.value);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>IBY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {showModal ? (
          <div className={styles.backdrop}>
            <div className={styles.modal}>
              <button className={styles.close} onClick={() => setShowModal(false)}>
                <Image
                  src="/close.svg"
                  alt="close"
                  width={75}
                  height={75}
                />
              </button>
              <h3>Please enter your Private Key</h3>
              <input
                className={styles.formInput}
                type="text"
                placeholder="Private Key"
                onChange={handleChangePK}
                style={{marginBottom: "15px"}}
                value={pk}
              />
              <button className={styles.btnPrimary} onClick={() => setShowModal(false)}>Submit</button>
            </div>
          </div>
        ) : null}
        <div className={styles.card}>
          <div className={styles.header}>
            <Image
              className={styles.logo}
              src="/logo.svg"
              alt="IBY Logo"
              width={75}
              height={75}
            />
            <button className={styles.btnConnect} onClick={() => setShowModal(true)}>Connect</button>
          </div>
          <div className={styles.controlContainer}>
            <h3>Current Bet Balance: 30</h3>
            <div className={styles.formContainer}>
              <input
                className={styles.formInput}
                placeholder="Amount"
                type="number"
                name="amount"
                value={amount}
                onChange={handleChangeAmount}
              />
              <button className={styles.btnPrimary}>Create Bet</button>
            </div>
            <div className={styles.buttonContainer}>
              <button className={styles.btnPrimary}>Join Bet</button>
            </div>
            <div className={styles.buttonContainer}>
              <button className={styles.btnPrimary}>Be Judge</button>
            </div>
            <div>
              <h3>Vote</h3>
              <div className={styles.formContainer}>
                <button className={styles.btnPrimaryOutline}>Bettor</button>
                <button className={styles.btnPrimaryOutline}>
                  Counter Bettor
                </button>
              </div>
            </div>
          </div>
          <div className={styles.powered}>Powered by IBY</div>
        </div>
      </main>
    </div>
  );
}
